### ISSUE TITLE
MissingPluginException(No implementation found for method set_home_wallpaper on channel async_wallpaper)

### ISSUE THREAD

**Issue by theatifwaheed** [codenameakshay/async_wallpaper#17]
I have Flutter 3.3.10 and There is an issue with this package. It works fine on Android but it crashes in ios iPhone 14 Pro Max. It gives me the following error mentioned in the title.

**Comment by codenameakshay** [comment]
This package currently only supports Android.
![image](https://user-images.githubusercontent.com/60510869/215947937-34b86139-a46f-42b8-8fad-b633ed5ce2bb.png)

If you want to contribute for iOS, you can.

**Comment by theatifwaheed** [comment]
Oh... Sorry for the inconvenience. I didn't saw this.
