### ISSUE TITLE
Live Wallpaper Feature not working

### ISSUE THREAD

**Issue by RAJJA111** [codenameakshay/async_wallpaper#2]
![image_2022_02_08T10_24_51_335Z](https://user-images.githubusercontent.com/98642473/152968486-86b46ebb-bb83-46ca-9b6f-c9fd1fab454b.png)
Live wallpaper feature not working.
it's shows this type of error

**Comment by codenameakshay** [comment]
Please attach logs for `flutter doctor -v`, and also mention your mobile manufacturer/Android details.

**Comment by RAJJA111** [comment]
![image](https://user-images.githubusercontent.com/98642473/153345441-bc3758fe-1bba-405a-81a7-828e0400c1a4.png)
![image](https://user-images.githubusercontent.com/98642473/153345583-2d8e3dfd-13ad-4626-891e-692fa34d4ecf.png)
device : realme narzo 50i

**Comment by RAJJA111** [comment]
please solve my issue because I need this hardly
