### ISSUE TITLE
how can i solve this ?

### ISSUE THREAD

**Issue by OrwaPog** [codenameakshay/async_wallpaper#5]
Attribute application@name value=(android.app.Application) from (unknown)
	is also present at [:async_wallpaper] AndroidManifest.xml:19:9-79 value=(com.codenameakshay.async_wallpaper.AsyncWallpaperPlugin).
	Suggestion: add 'tools:replace="android:name"' to <application> element at AndroidManifest.xml:6:4-50:19 to override.

**Comment by unesbnn** [comment]
This is how I solved it

In your AndroidManifest.xml
Add this line inside<manifest>: xmlns:tools="http://schemas.android.com/tools"
And this line inside <application>: tools:replace="android:name"
